### ISSUE TITLE
Correction in print statement in sample.py

### ISSUE THREAD

**Issue by prabhupant** [fossasia/susi_api_wrapper#71]
In line 19,
`print('Server''s Message:')` should be written as `print("Server's Message')`

**Comment by SubhamPaul21** [comment]
is this issue still open or its done?

**Comment by prabhupant** [comment]
@SubhamPaul21  it has the PR filed and approved....waiting to be merged

**Comment by SubhamPaul21** [comment]
Ok that's fine 👍
